---
- hosts: buildserver
  vars:
    warName: sample.war
    tomcat_version: 8.5.98
    warRemotePath: /opt/apache-tomcat-{{ tomcat_version }}/webapps

  tasks:
  - name: ping buildserver
    ping:

  - name: Copy WAR to Remote server
    become: true
    copy: 
      src: "/home/labsuser/ansible_project/{{ warName }}" 
      dest: "{{ warRemotePath }}/{{ warName }}" 
      owner: tomcat 
      group: tomcat
      #remote_src: yes

